<?php
	/*admin only*/
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Global Settings', $this->pluginLocale),__('Settings', $this->pluginLocale), 'wppizza_cap_settings', $this->pluginSlug.'-settings', array($this, 'admin_manage_settings'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Order Settings', $this->pluginLocale),__('&middot; Order Settings', $this->pluginLocale), 'wppizza_cap_order_settings',  $this->pluginSlug.'-order-settings', array($this, 'admin_manage_order_settings'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Order Form', $this->pluginLocale),__('&middot; Order Form Settings', $this->pluginLocale), 'wppizza_cap_order_form_settings',  $this->pluginSlug.'-order-form', array($this, 'admin_manage_order_form'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Opening Times', $this->pluginLocale),__('&middot; Opening Times', $this->pluginLocale), 'wppizza_cap_opening_times', $this->pluginSlug.'-opening-times', array($this, 'admin_manage_opening_times'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Gateways', $this->pluginLocale),__('&middot; Gateways', $this->pluginLocale), 'wppizza_cap_gateways',  $this->pluginSlug.'-gateways', array($this, 'admin_manage_gateways'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Meal Sizes', $this->pluginLocale),__('&middot; Meal Sizes', $this->pluginLocale), 'wppizza_cap_meal_sizes',  $this->pluginSlug.'-meal-sizes', array($this, 'admin_manage_meal_sizes'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Additives', $this->pluginLocale),__('&middot; Additives', $this->pluginLocale), 'wppizza_cap_additives',  $this->pluginSlug.'-additives', array(&$this,'admin_manage_additives'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Layout', $this->pluginLocale),__('&middot; Layout', $this->pluginLocale), 'wppizza_cap_layout', $this->pluginSlug.'-layout', array($this, 'admin_manage_layout'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Localization', $this->pluginLocale),__('&middot; Localization', $this->pluginLocale), 'wppizza_cap_localization', $this->pluginSlug.'-localization', array($this, 'admin_manage_localization'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Order History', $this->pluginLocale),__('&middot; Order History', $this->pluginLocale), 'wppizza_cap_order_history',  $this->pluginSlug.'-order-history', array($this, 'admin_manage_order_history'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Reports', $this->pluginLocale),__('&middot; Reports', $this->pluginLocale), 'wppizza_cap_reports',  $this->pluginSlug.'-reports', array($this, 'admin_manage_reports'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Manage Access Rights', $this->pluginLocale),__('&middot; Access Rights', $this->pluginLocale), 'wppizza_cap_access',  $this->pluginSlug.'-access-rights', array($this, 'admin_manage_access_rights'));
	add_submenu_page('edit.php?post_type='.$this->pluginSlug.'',$this->pluginName.' '.__('Tools', $this->pluginLocale),__('&middot; Tools', $this->pluginLocale), 'wppizza_cap_tools',  $this->pluginSlug.'-tools', array($this, 'admin_manage_tools'));
?>